env:
  browser: true
  es2021: true
extends:
  - 'plugin:@typescript-eslint/recommended-type-checked'
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
root: true
parserOptions:
  project: true
  tsconfigRootDir: __dirname
  ecmaVersion: latest
  sourceType: module
  files: ['**/*.ts']
  ignores: ['**/*.config.js']
  extends:
    - prettier
rules:
  space-before-function-paren: off
  "@typescript-eslint/space-before-function-paren": off
  "@typescript-eslint/no-unused-vars":
    - warn
    - argsIgnorePattern: '^_'
      varsIgnorePattern: '^_'
  "@typescript-eslint/restrict-plus-operands":
    - warn
    - skipCompoundAssignments: true